# Generated by Django 2.2 on 2019-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='blog/static/blog/upload_image/201904/24'),
        ),
    ]
