# Generated by Django 2.2 on 2019-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190424_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog/static/blog/upload_image/201904/24'),
        ),
    ]
